global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Target the Prometheus service

  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:8000'] # Target your backend service