global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # Target the Prometheus service

  - job_name: 'backend'
    static_configs:
      - targets: ['tr_back:${DJANGO_PORT}'] # Target your backend service